# Generated by Django 4.2.3 on 2024-02-10 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='adresse',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employe',
            name='affectOrigine',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employe',
            name='dateRecrutement',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='employe',
            name='dernierPointage',
            field=models.CharField(choices=[('1', '1'), ('7', '7'), ('Cr', 'Cr'), ('2', '2'), ('R', 'R'), ('8', '8'), ('I', 'I'), ('T', 'T'), ('C', 'C'), ('6', '6'), ('9', '9'), ('A', 'A'), ('M', 'M')], default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='employe',
            name='fonction',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employe',
            name='nbrEnfants',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='employe',
            name='situationFamiliale',
            field=models.CharField(choices=[('marié', 'marié(e)'), ('divorcé', 'divorcé(e)'), ('célibataire', 'célibataire'), ('veuf', 'veuf(ve)')], max_length=100, null=True),
        ),
    ]
