# Generated by Django 5.0.2 on 2024-02-12 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_employe_adresse_alter_employe_affectorigine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='dateDernierPointage',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='employe',
            name='dernierPointage',
            field=models.CharField(choices=[('I', 'I'), ('M', 'M'), ('8', '8'), ('R', 'R'), ('Cr', 'Cr'), ('9', '9'), ('A', 'A'), ('T', 'T'), ('C', 'C'), ('2', '2'), ('6', '6'), ('1', '1'), ('7', '7')], default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='employe',
            name='situationFamiliale',
            field=models.CharField(choices=[('célibataire', 'célibataire'), ('divorcé', 'divorcé(e)'), ('marié', 'marié(e)'), ('veuf', 'veuf(ve)')], max_length=100, null=True),
        ),
    ]
